/*
 ******************************************************************************
 File:     main.c
 Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2020-02-03

 The MIT License (MIT)
 Copyright (c) 2019 STMicroelectronics

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 ******************************************************************************
 */

/* Includes */
#include <stddef.h>
#include "stm32l0xx.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
 **===========================================================================
 **
 **  Abstract: main program
 **
 **===========================================================================
 */
int main(void) {
	uint32_t ii = 0;

	/* TODO - Add your application code here */
	ADC1->CR &= ~ADC_CR_ADEN;

	// ADC Calibration ch 14.11.3
	ADC1->CR |= ADC_CR_ADCAL;
	// wait for calibration
	while ((ADC1->CR & ADC_CR_ADCAL) != 0) {

	}

	// Enable ADC clock
	// Select a clock source for the ADC ch 7.3.14
	RCC->APB2ENR |= RCC_APB2ENR_ADC1EN;

	RCC->CR |= RCC_CR_HSION;
	while ((RCC->CR & RCC_CR_HSIRDY) == 0) {

	}

	// Ch 14 Analog-to-digital converter

	// ADC Enable

	// start adc conversion
	ADC1->CR |= ADC_CR_ADSTART;

	// wait for ADC to complete conversion
	while ((ADC1->CR & ADC_CR_ADSTART) != 0) {

	}
	// read the adc data, ch 14.11.9 ADC data register(ADC_DR)

	while (1) {
		ii++;
	}

	return 0;
}
