/*
 ******************************************************************************
 File:     main.c
 Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2020-02-04

 The MIT License (MIT)
 Copyright (c) 2019 STMicroelectronics

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 ******************************************************************************
 */

/* Includes */
#include <stddef.h>
#include "stm32l0xx.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */
volatile int32_t TimeDelay;
void SysTick_Handler() {
	if (TimeDelay > 0)
		TimeDelay--;
}
void Delay(uint32_t nTime) {
	TimeDelay = nTime;
 	while (TimeDelay != 0)
		;
}

void Systic_Init(uint32_t ticks) {

	//0xE000E010
	SysTick->CTRL = 0; // disable Systic
	SysTick->LOAD = ticks - 1; // Set reload register
	//Set interrupt priority of SysTic to least urgency (i.e., largest priority value)
	NVIC_SetPriority(SysTick_IRQn, (1 << __NVIC_PRIO_BITS) - 1);
	SysTick->VAL = 0;

	// Select processor clock: 1=Processor clock, 0=external clock
	//SysTick->CTRL |= SysTick_CTRL_CLKSOURCE_Msk;

	// Enables SysTick interrupt, 1=Enable, 0=Disable;
	SysTick->CTRL |= 1 << 1;

	// Enables SysTick
	SysTick->CTRL |= 1;

}

int main(void) {

	Systic_Init(262);
//RCC_ICSCR_MSIRANGE_6;
	RCC->IOPENR |= RCC_IOPENR_GPIOAEN; // Enable GPIOA Clock.
	GPIOA->MODER &= ~(0x1 << 1); // PA0 as output
	/* TODO - Add your application code here */
	while (1) {

		Delay(500);
		static uint8_t flag = 0;

		if (flag) {
			flag = 0;
			GPIOA->BSRR = 1;
		} else {
			flag = 1;
			GPIOA->BRR = 1;
		}
	}
	return 0;
}

//void SystemClockInit(void){
//	RCC->CR |= RCC_CR_MSION;
//
//	// Select MSI as the clock source of System Clock
//	RCC->CR &= ~RCC_CFGR_SW;
//
//	// Wait until MSI is reay
//	while((RCC->CR & RCC_CR_MSIRDY) == 0);
//
//	// MSIRANGE can be modified when MSI is OFF
//	RCC->CR |= ~RCC_ICSCR_MSIRANGE_6;
//
//	#define Tick TimeDelay
//#define CLOCKSWITCH_TIMEOUT_VALUE 100
//#define PLL_TIMEOUT_VALUE 3
//	uint32_t tickStart;
//	RCC->CFGR = (RCC->CFGR &(~RCC_CFGR_SW)) | RCC_CFGR_SWS_HSI;
//	tickStart = Tick;
//	while((RCC->CFGR & RCC_CFGR_SWS) != RCC_CFGR_SWS_HSI){
//		if((Tick - tickStart) > CLOCKSWITCH_TIMEOUT_VALUE){
//			/* Manage error*/
//			return;
//		}
//	}
//	RCC->CR &= ~RCC_CR_PLLON;
//	tickStart = Tick;
//	while((RCC->CR & RCC_CR_PLLRDY) != 0){
//		if((Tick - tickStart) > PLL_TIMEOUT_VALUE){
//			/* Manage error*/
//		}
//	}
//}

